services:
  mongo:
    image: mongo:6
    container_name: sports-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017/admin", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: sports-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://sports-mongo:27017/sportsdb
      BACKEND_URL: http://sports-backend:5000

      PORT: 5000
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

  frontend:
    image: himanshi1409/sports-frontend:latest
    build: ./frontend
    container_name: sports-frontend
    ports:
      - "3000:4173"
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:


